[Eth]
NetworkId = 1357
SyncMode = "full"
LightPeers = 100
DatabaseCache = 768
EnablePreimageRecording = false

[Node]
DataDir ="/home/hlf/geth/data/00"
IPCPath = "geth.ipc"
HTTPHost = "127.0.0.1"
HTTPPort = 8545
WSPort = 8546

[Node.P2P]
MaxPeers = 25
ListenAddr = ":30303"
